
CREATE TABLE IF NOT EXISTS flare_profile (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_key VARCHAR(24) UNIQUE,
    server_brand VARCHAR(255) NOT NULL,
    server_version VARCHAR(255) NOT NULL,
    os_family VARCHAR(255) NOT NULL,
    os_version VARCHAR(255) NOT NULL,
    jvm_vendor VARCHAR(255) NOT NULL,
    jvm_version VARCHAR(255) NOT NULL,
    raw BYTEA NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS flare_sample_data (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_key VARCHAR(24) NOT NULL,
    raw BYTEA NOT NULL,
    CONSTRAINT fk_sample_data_profile
        FOREIGN KEY (profile_key)
        REFERENCES flare_profile(profile_key)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_sample_data_profile_key ON flare_sample_data(profile_key);

CREATE TABLE IF NOT EXISTS flare_sample_timeline (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_key VARCHAR(24) NOT NULL,
    raw BYTEA NOT NULL,
    CONSTRAINT fk_sample_timeline_profile
        FOREIGN KEY (profile_key)
        REFERENCES flare_profile(profile_key)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_sample_timeline_profile_key ON flare_sample_timeline(profile_key);
